// Disamakan persis dengan frontend/src/index.css agar identitas PawCare konsisten
export const colors = {
  cream: '#FFF8F0',
  warmBg: '#FFF2E4',
  card: '#FFFFFF',
  orange: '#FF7A3D',
  orangeDk: '#E5692E',
  orangeLt: '#FFE5D6',
  peach: '#FFBFA0',
  teal: '#3DBFB8',
  tealLt: '#D6F4F3',
  yellow: '#FFD166',
  yellowLt: '#FFF5D6',
  pink: '#FF6B9D',
  pinkLt: '#FFE0EE',
  purple: '#9B72CF',
  purpleLt: '#EDE4F8',
  green: '#4CAF82',
  greenLt: '#DDF3EA',
  red: '#FF5252',
  redLt: '#FFE5E5',
  blue: '#4A90D9',
  blueLt: '#DDEEFF',
  textDark: '#2D1B0E',
  textMid: '#6B4C35',
  textSoft: '#A07A60',
  border: '#F0DFD0',
}
